/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RadioRouteImport } from './routes/radio'
import { Route as BillboardsRouteImport } from './routes/billboards'
import { Route as IndexRouteImport } from './routes/index'

const RadioRoute = RadioRouteImport.update({
  id: '/radio',
  path: '/radio',
  getParentRoute: () => rootRouteImport,
} as any)
const BillboardsRoute = BillboardsRouteImport.update({
  id: '/billboards',
  path: '/billboards',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/billboards': typeof BillboardsRoute
  '/radio': typeof RadioRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/billboards': typeof BillboardsRoute
  '/radio': typeof RadioRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/billboards': typeof BillboardsRoute
  '/radio': typeof RadioRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/billboards' | '/radio'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/billboards' | '/radio'
  id: '__root__' | '/' | '/billboards' | '/radio'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BillboardsRoute: typeof BillboardsRoute
  RadioRoute: typeof RadioRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/radio': {
      id: '/radio'
      path: '/radio'
      fullPath: '/radio'
      preLoaderRoute: typeof RadioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billboards': {
      id: '/billboards'
      path: '/billboards'
      fullPath: '/billboards'
      preLoaderRoute: typeof BillboardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BillboardsRoute: BillboardsRoute,
  RadioRoute: RadioRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
