/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RadioRouteImport } from './routes/radio'
import { Route as PanneauxRouteImport } from './routes/panneaux'
import { Route as IndexRouteImport } from './routes/index'

const RadioRoute = RadioRouteImport.update({
  id: '/radio',
  path: '/radio',
  getParentRoute: () => rootRouteImport,
} as any)
const PanneauxRoute = PanneauxRouteImport.update({
  id: '/panneaux',
  path: '/panneaux',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/panneaux': typeof PanneauxRoute
  '/radio': typeof RadioRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/panneaux': typeof PanneauxRoute
  '/radio': typeof RadioRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/panneaux': typeof PanneauxRoute
  '/radio': typeof RadioRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/panneaux' | '/radio'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/panneaux' | '/radio'
  id: '__root__' | '/' | '/panneaux' | '/radio'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PanneauxRoute: typeof PanneauxRoute
  RadioRoute: typeof RadioRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/radio': {
      id: '/radio'
      path: '/radio'
      fullPath: '/radio'
      preLoaderRoute: typeof RadioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panneaux': {
      id: '/panneaux'
      path: '/panneaux'
      fullPath: '/panneaux'
      preLoaderRoute: typeof PanneauxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PanneauxRoute: PanneauxRoute,
  RadioRoute: RadioRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
